// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_adois.Data;

#nullable disable

namespace api_adois.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107215228_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api_adois.Models.Destinos", b =>
                {
                    b.Property<int>("IdDes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgDestino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ImagemDoDestino");

                    b.Property<string>("NomeDes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NomeDoDestino");

                    b.HasKey("IdDes");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            IdDes = 1,
                            ImgDestino = "https://blog.123milhas.com/wp-content/uploads/2023/03/aniversario-do-rio-de-janeiro-conheca-quatro-curiosidades-sobre-a-cidade-conexao123.jpg",
                            NomeDes = "Rio de Janeiro"
                        },
                        new
                        {
                            IdDes = 2,
                            ImgDestino = "https://revistaazul.voeazul.com.br/wp-content/uploads/2023/03/conheca-salvador-e-se-apaixone-pela-capital-baiana.jpeg",
                            NomeDes = "Salvador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
