// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_adois.Data;

#nullable disable

namespace api_adois.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api_adois.Models.Destinos", b =>
                {
                    b.Property<int>("IdDes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgDestino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ImagemDoDestino");

                    b.Property<string>("NomeDes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NomeDoDestino");

                    b.Property<int>("PrecoDest")
                        .HasColumnType("int")
                        .HasColumnName("PrecoDest");

                    b.HasKey("IdDes");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            IdDes = 1,
                            ImgDestino = "https://blog.123milhas.com/wp-content/uploads/2023/03/aniversario-do-rio-de-janeiro-conheca-quatro-curiosidades-sobre-a-cidade-conexao123.jpg",
                            NomeDes = "Rio de Janeiro",
                            PrecoDest = 300
                        },
                        new
                        {
                            IdDes = 2,
                            ImgDestino = "https://revistaazul.voeazul.com.br/wp-content/uploads/2023/03/conheca-salvador-e-se-apaixone-pela-capital-baiana.jpeg",
                            NomeDes = "Salvador",
                            PrecoDest = 300
                        },
                        new
                        {
                            IdDes = 3,
                            ImgDestino = "https://wordpress-network.prod.aws.skyscnr.com/wp-content/uploads/2018/05/GettyImages-488388458.jpg",
                            NomeDes = "Foz do Iguaçu",
                            PrecoDest = 350
                        },
                        new
                        {
                            IdDes = 4,
                            ImgDestino = "https://www.falandodeviagem.com.br/imagens22/Guaruja.jpg",
                            NomeDes = "Guarujá",
                            PrecoDest = 100
                        },
                        new
                        {
                            IdDes = 5,
                            ImgDestino = "https://media.tacdn.com/media/attractions-splice-spp-674x446/09/93/6a/89.jpg",
                            NomeDes = "Londres",
                            PrecoDest = 1000
                        },
                        new
                        {
                            IdDes = 6,
                            ImgDestino = "https://www.remessaonline.com.br/blog/wp-content/uploads/2022/06/morar-em-nova-york-1170x777.jpg.webp",
                            NomeDes = "Nova York",
                            PrecoDest = 2300
                        },
                        new
                        {
                            IdDes = 7,
                            ImgDestino = "https://www.kayak.com.br/rimg/himg/4f/2d/0e/leonardo-2672017-DPSHA_4636182078_O-333430.jpg?width=1366&height=768&crop=true",
                            NomeDes = "Bali",
                            PrecoDest = 2000
                        },
                        new
                        {
                            IdDes = 8,
                            ImgDestino = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq5O8R9NyYOH6bOyYwCCMj4cu7ymj6PMLd1M1ySCdUfesRAZs6_ZyM-6GVV003r8JwZO0&usqp=CAU",
                            NomeDes = "Dubai",
                            PrecoDest = 3300
                        },
                        new
                        {
                            IdDes = 9,
                            ImgDestino = "https://blog.123milhas.com/wp-content/uploads/2023/08/brasileiros-na%CC%83o-precisam-mais-de-visto-para-turismo-no-japa%CC%83o-monte-fuji-conexa%CC%83o123.jpg",
                            NomeDes = "Japão",
                            PrecoDest = 1500
                        },
                        new
                        {
                            IdDes = 10,
                            ImgDestino = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo1wwNTG-MmPHGs2qVivurSlcz1LFNeYyg4BwhVwNcm2-wRWqrLwzkr5SVmEufdSQEuIg&usqp=CAU",
                            NomeDes = "Veneza",
                            PrecoDest = 2000
                        },
                        new
                        {
                            IdDes = 11,
                            ImgDestino = "https://www.passagenspromo.com.br/blog/wp-content/uploads/2019/04/viagem-para-paris.jpg",
                            NomeDes = "Paris",
                            PrecoDest = 1500
                        },
                        new
                        {
                            IdDes = 12,
                            ImgDestino = "https://blog.abreutur.com.br/wp-content/uploads/2022/01/CAPA_Egito.jpg",
                            NomeDes = "Egito",
                            PrecoDest = 900
                        },
                        new
                        {
                            IdDes = 13,
                            ImgDestino = "https://www.adventureclub.com.br/wp-content/uploads/2022/06/Bali-Indonesia-topo.jpg",
                            NomeDes = "Indonésia",
                            PrecoDest = 1500
                        },
                        new
                        {
                            IdDes = 14,
                            ImgDestino = "https://dynl.mktgcdn.com/p/PdKIFm42x4ilTlmQqIo-hn9SeaU0eEOojHALpH1XPwc/540x450.jpg",
                            NomeDes = "Maldivas",
                            PrecoDest = 3300
                        },
                        new
                        {
                            IdDes = 15,
                            ImgDestino = "https://www.remessaonline.com.br/blog/wp-content/uploads/2022/03/abrir-uma-empresa-na-Australia-1-2-1200x675.jpg",
                            NomeDes = "Austrália",
                            PrecoDest = 2300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
